### ISSUE TITLE
Sound hardlocks to 0

### ISSUE THREAD

**Issue by HalJordan** [Linux74656/SpaceEngineersLinuxPatches#22]
Both the normal sound bar and the music one are locked to 0. I can adjust, and save, but no change happens, and when I go back to the settings, they're back to 0.

**Comment by Linux74656** [comment]
You may try installing xact instead of faudio and recreating the prefix.

Otherwise you can try editing the config file in your prefix found at ..../Steam/steamapps/compatdata/244850/pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/SpaceEngineers.cfg

Find and change the value under:

`<Key>GameVolume</Key>`
`<Value xsi:type="xsd:string">0.0</Value>`

to something like `<Value xsi:type="xsd:string">0.5</Value>` values are  from 0 to 1 so adjust to your liking.

You can change music volume with the key: `<Key>Music_Volume</Key>`

**Comment by Linux74656** [comment]
I have closed this as I assume it is no longer an issue.
