### ISSUE TITLE
SE does not handle NFS shares

### ISSUE THREAD

**Issue by Phalen** [Linux74656/SpaceEngineersLinuxPatches#33]
Please add in to the notes SE can not be installed on a nfs share. mein_nick_ist_besetzt and I both ran in to the same issue.

"Exception occured: System.IO.FileLoadException: Could not load file or assembly"  is the part from the logs as soon as you move the files from the nfs share it works normally.

**Comment by Linux74656** [comment]
Got it. It has been added to the list of issues!

**Comment by FeepingCreature** [comment]
I added `<loadFromRemoteSources enabled="true"/>` to `<runtime>` in SpaceEngineers.exe.config and that seems to have allowed it to start. I think Proton, not incorrectly, registers NFS as a network drive.

**Comment by glabifrons** [comment]
The fix mentioned by @FeepingCreature has been added to GE Proton 10-26.
https://github.com/GloriousEggroll/proton-ge-custom/issues/355

Note that GE Proton will only patch this file if the file SpaceEngineers.exe.config.protonfixes.bak *does not* exist.
Simply mv SpaceEngineers.exe.config.protonfixes.bak SpaceEngineers.exe.config to put the stock file back in place before launching the game using Proton 10-26.
Probably also best to rename your 244850 subdirectory before launching the game to have it cleanly rebuilt as well, as there are other fixes applied by GE Proton that may conflict with older fixes.
I say "rename" rather than "delete" as you likely want your old saves and any custom blueprints you created.
