### ISSUE TITLE
GPU Driver has crashed error

### ISSUE THREAD

**Issue by 3top1a** [Linux74656/SpaceEngineersLinuxPatches#41]
After (somehow) managing to start SE I made a new world.
After selecting earth pod this error came up (after the audio started)

![Screenshot_2020-09-09_19-21-26](https://user-images.githubusercontent.com/57371001/92630948-e954f580-f2d0-11ea-8a8f-dc30ac51b737.png)
[SpaceEngineers_20200909_191704380.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5196929/SpaceEngineers_20200909_191704380.log)
[VRageRender-DirectX11_20200909_191715785.log](https://github.com/Linux74656/SpaceEngineersLinuxPatches/files/5196931/VRageRender-DirectX11_20200909_191715785.log)

**Comment by 3top1a** [comment]
Just looked at the mangohud, the VRAM was full.

**Comment by 3top1a** [comment]
One of the SE instances zombied, eating up all the VRAM

**Comment by Linux74656** [comment]
Yeah. I have seen this error a lot when using my old gtx 960 2gb, card, especially when using opengl/directX instead of vulkan.
I never really found a solution other than more vram, or keeping SE vram usage to a minimum.
Since your card is not vulkan capable, and has limited vram, i do not really have any suggestions that may be helpful.
